package com.guyo.archive_system.document.dto;

import java.util.UUID;

import com.guyo.archive_system.document.enums.ClassificationLevel;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Payload for creating a new document.
 * <p>
 * {@code status} is deliberately not a field here — every document starts
 * life as DRAFT (see {@link com.guyo.archive_system.document.service.DocumentServiceImpl}),
 * and every subsequent status change goes through the workflow module so
 * it is recorded in document_workflow_history. Allowing status to be set
 * directly here would let a document skip that audit trail entirely.
 * <p>
 * {@code referenceNumber} is also not a field here — it is generated by
 * the {@code trg_generate_document_reference} trigger (V6) on insert.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CreateDocumentRequest {

    @NotBlank(message = "title is required")
    @Size(max = 300, message = "title must be at most 300 characters")
    private String title;

    private String description;

    @NotNull(message = "categoryId is required")
    private UUID categoryId;

    @NotNull(message = "departmentId is required")
    private UUID departmentId;

    /** Optional; defaults to INTERNAL (matching the database default) if omitted. */
    private ClassificationLevel classification;
}
